import type { Metadata } from "next";
import { Geist, Geist_Mono, ABeeZee, Inter, Comforter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const abeeZee = ABeeZee({
  variable: "--font-abee-zee",
  subsets: ["latin"],
  weight: "400",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const comforter = Comforter({
  variable: "--font-comforter",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Hello World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  team,
  analytics,
}: Readonly<{
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body >
        <AntdRegistry>
          <div className="container mx-auto">
            <div className="flex justify-center gap-6 p-6 text-blue-500">
              <Link href="/"> Home </Link>
              <Link href="/visitors"> Visitors </Link>
            </div>
            <div className="flex gap-6 p-6">
              {team}
              {analytics}
            </div>
            <div className="px-6 pb-6">
              {children}
            </div>
          </div>
        </AntdRegistry>
      </body>

    </html>
  );
}
